"""Independent frozen source census vs captured SQL ownership and representation."""
import argparse,collections,datetime,hashlib,json
from pathlib import Path
from f4_semantic_compare import rows,diff,save

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--census',required=True,type=Path);ap.add_argument('--snapshot',required=True,type=Path);ap.add_argument('--out',required=True,type=Path);a=ap.parse_args();census=json.loads(a.census.read_text());snapshot=json.loads(a.snapshot.read_text());t={k:rows(snapshot,k) for k in snapshot['tables']};docs={d['record_key']:d for d in t['catalogue_documents']};docids={d['id']:d for d in t['catalogue_documents']};srcids={s['id']:s for s in t['source_descriptions']};workids={w['id']:w for w in t['works']};observations=[];checks=[]
 def check(id,expected,observed):
  mismatch=diff(expected,observed);checks.append({'id':id,'status':'PASS' if not mismatch else 'FAIL','mismatches':mismatch})
 check('document_total',len(census['files']),len(t['catalogue_documents']));check('work_total',len(census['files']),len(t['works']))
 check('document_key_uniqueness',len(t['catalogue_documents']),len(docs));check('document_fk_work_orphans',0,sum(w['catalogue_document_id'] not in docids for w in t['works']));check('document_fk_source_orphans',0,sum(s['catalogue_document_id'] not in docids for s in t['source_descriptions']))
 check('source_xml_document_uniqueness',len(t['source_descriptions']),len({(s['catalogue_document_id'],s['xml_id']) for s in t['source_descriptions']}));check('item_xml_document_uniqueness',len(t['held_items']),len({(i['catalogue_document_id'],i['xml_id']) for i in t['held_items']}));check('item_source_same_document',0,sum(i['source_description_id'] not in srcids or srcids[i['source_description_id']]['catalogue_document_id']!=i['catalogue_document_id'] for i in t['held_items']))
 check('relation_owner_same_document',0,sum(r['source_description_id'] not in srcids or srcids[r['source_description_id']]['catalogue_document_id']!=r['catalogue_document_id'] for r in t['source_relations']));check('relation_target_source_same_document',0,sum(r['target_source_description_id'] is not None and (r['target_source_description_id'] not in srcids or srcids[r['target_source_description_id']]['catalogue_document_id']!=r['catalogue_document_id']) for r in t['source_relations']));check('relation_target_work_same_document',0,sum(r['target_work_id'] is not None and (r['target_work_id'] not in workids or workids[r['target_work_id']]['catalogue_document_id']!=r['catalogue_document_id']) for r in t['source_relations']))
 for expected in census['files']:
  key=expected['record_key'];d=docs.get(key)
  if d is None:check('record/'+key+'/exists',True,False);continue
  work=[w for w in t['works'] if w['catalogue_document_id']==d['id']];check('record/'+key+'/work_count',1,len(work));check('record/'+key+'/hash',expected['sha256'],d['committed_sha256']);check('record/'+key+'/profile','official_cnw_v401',d['input_profile']);check('record/'+key+'/root',expected['root_xml_id'],d['root_xml_id']);check('record/'+key+'/work_xml_id',expected['work_xml_id'],work[0]['source_identifier'] if work else None);check('record/'+key+'/summary',expected['projection_summary'],d['source_projection_summary']);sources=[]
  for s in sorted([s for s in t['source_descriptions'] if s['catalogue_document_id']==d['id']],key=lambda s:(s['source_order'],s['id'])):
   sd={k:s[k] for k in ['xml_id','locator','source_order','state']};fields=['identifiers','titles','classification_terms','publication','physical_description','notes','links'];sd['selected_value_counts']={k:len(s[k]) for k in fields};sd['selected_blank_value_counts']={k:sum(v['text'] is None for v in s[k]) for k in fields};sd['held_items']=[{k:i[k] for k in ['xml_id','locator','source_order','state']}|{'source_xml_id':s['xml_id']} for i in sorted([i for i in t['held_items'] if i['source_description_id']==s['id']],key=lambda i:(i['source_order'],i['id']))];sd['relations']=[]
   for r in sorted([r for r in t['source_relations'] if r['source_description_id']==s['id']],key=lambda r:(r['relation_order'],r['token_order'],r['id'])):
    rd={k:r[k] for k in ['xml_id','locator','relation_order','token_order','rel','raw_target','target_token','resolution_state','resolution_reason']};rd.update({'source_xml_id':s['xml_id'],'target_source_xml_id':None if r['target_source_description_id'] is None else srcids[r['target_source_description_id']]['xml_id'],'expression_xml_id':None if not r['expression_context'] else r['expression_context']['xml_id'],'expression_locator':None if not r['expression_context'] else r['expression_context']['locator'],'expression_work_xml_id':None if not r['expression_context'] else r['expression_context']['containing_work']['xml_id']});sd['relations'].append(rd)
   sources.append(sd)
  check('record/'+key+'/source_ownership_state_fields_and_relations',expected['sources'],sources);observations.append({'record_key':key,'filename':expected['filename'],'sha256':expected['sha256'],'document_id':d['id'],'work_ids':[w['id'] for w in work],'summary':d['source_projection_summary'],'sources':sources})
 summary={'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'PASS' if all(c['status']=='PASS' for c in checks) else 'FAIL','checks':len(checks),'passed':sum(c['status']=='PASS' for c in checks),'failed':sum(c['status']=='FAIL' for c in checks),'documents':len(t['catalogue_documents']),'works':len(t['works']),'source_descriptions':len(t['source_descriptions']),'held_items':len(t['held_items']),'source_relations':len(t['source_relations']),'source_states':dict(collections.Counter(r['state'] for r in t['source_descriptions'])),'item_states':dict(collections.Counter(r['state'] for r in t['held_items'])),'relation_states':dict(collections.Counter(r['resolution_state'] for r in t['source_relations'])),'relation_reasons':dict(collections.Counter(str(r['resolution_reason']) for r in t['source_relations'])),'inputs':[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [a.census,a.snapshot]]};save(a.out/'census_checks.json',checks);save(a.out/'census_sql_observations.json',observations);save(a.out/'census_summary.json',summary);print(json.dumps(summary,indent=2))
 raise SystemExit(0 if summary['status']=='PASS' else 1)
if __name__=='__main__':main()
